CREATE TABLE IF NOT EXISTS hr."HrReviewCycle" (
 "id" SERIAL PRIMARY KEY, "name" VARCHAR(150) NOT NULL,
 "startDate" DATE NOT NULL, "endDate" DATE NOT NULL, "description" TEXT,
 "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK ("endDate" >= "startDate")
);
CREATE TABLE IF NOT EXISTS hr."HrReview" (
 "id" SERIAL PRIMARY KEY, "employeeId" INTEGER NOT NULL REFERENCES hr."Employee"("id"),
 "reviewerId" INTEGER NOT NULL REFERENCES hr."Employee"("id"), "cycleId" INTEGER NOT NULL REFERENCES hr."HrReviewCycle"("id"),
 "name" VARCHAR(150) NOT NULL, "goals" TEXT NOT NULL, "selfReview" TEXT, "managerReview" TEXT,
 "rating" INTEGER CHECK ("rating" BETWEEN 1 AND 5), "status" VARCHAR(30) NOT NULL DEFAULT 'SELF_REVIEW' CHECK ("status" IN ('SELF_REVIEW','MANAGER_REVIEW','FINAL')),
 "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "HrReview_employeeId_cycleId_key" UNIQUE ("employeeId", "cycleId"), CHECK ("employeeId" <> "reviewerId")
);
CREATE TABLE IF NOT EXISTS hr."HrDocument" (
 "id" SERIAL PRIMARY KEY, "employeeId" INTEGER NOT NULL REFERENCES hr."Employee"("id"),
 "name" VARCHAR(150) NOT NULL, "category" VARCHAR(30) NOT NULL, "url" TEXT NOT NULL, "expiryDate" DATE, "description" TEXT,
 "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
