import { weeklyHours } from "./schedule-hours.mjs";
export const human = value => String(value ?? "").replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const field = (key, label, type = "text", extra = {}) => ({ key, label, type, ...extra });
const select = (key, label, options, extra = {}) => field(key, label, "select", { options, ...extra });
const relation = (key, label, source, extra = {}) => field(key, label, "relation", { source, ...extra });
const optional = { optional: true };
const named = [field("code", "Code"), field("name", "Name")];
const active = field("isActive", "Active", "checkbox", { default: true });
const note = field("description", "Description", "textarea", optional);
const employee = relation("employeeId", "Employee", "employees");
const types = ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERN", "TEMPORARY"];
const frequencies = ["MONTHLY", "SEMI_MONTHLY", "BIWEEKLY", "WEEKLY", "CUSTOM"];
const range = [field("startDate", "Start date", "date"), field("endDate", "End date", "date", optional)];
export const configs = {
  employees: { noCreate: true, help: "Employees appear automatically when an administrator creates an Employee workspace account in Users and roles. Edit a profile to complete its employment details.", title: "Employees", singular: "employee", columns: [["employeeCode", "Code"], ["firstName", "First name"], ["lastName", "Last name"], ["department.name", "Department"], ["hireDate", "Joined"], ["status", "Status"]], fields: [field("employeeCode", "Employee code"), field("firstName", "First name"), field("lastName", "Last name", "text", optional), field("workEmail", "Work email", "email", optional), field("workPhone", "Work phone", "text", optional), relation("departmentId", "Department", "departments", optional), relation("jobPositionId", "Job position", "positions", optional), relation("managerId", "Manager", "employees", optional), select("employeeType", "Employment type", types, { default: "FULL_TIME" }), select("status", "Status", ["ONBOARDING", "ACTIVE", "ON_LEAVE", "SUSPENDED", "TERMINATED", "ARCHIVED"], { default: "ACTIVE" }), field("hireDate", "Joining date", "date"), field("terminationDate", "Termination date", "date", optional), field("workLocation", "Work location", "text", optional), field("notes", "Notes", "textarea", optional)], archive: true },
  departments: { title: "Departments", singular: "department", columns: [["code", "Code"], ["name", "Name"], ["isActive", "Active"]], fields: [...named, note, active], archive: true },
  positions: { title: "Job positions", singular: "job position", columns: [["code", "Code"], ["title", "Title"], ["department.name", "Department"], ["isActive", "Active"]], fields: [field("code", "Code"), field("title", "Title"), relation("departmentId", "Department", "departments", optional), note, active], archive: true },
  contracts: { title: "Contracts", singular: "contract", columns: [["reference", "Reference"], ["employee", "Employee"], ["startDate", "Start"], ["endDate", "End"], ["wage", "Wage"], ["currency", "Currency"], ["status", "Status"]], fields: [field("reference", "Reference"), field("name", "Contract name"), employee, relation("departmentId", "Department", "departments"), relation("jobPositionId", "Job position", "positions"), select("employeeType", "Employment type", types, { default: "FULL_TIME" }), ...range, field("probationEndDate", "Probation end", "date", optional), field("terminationDate", "Termination date", "date", optional), select("status", "Status", ["DRAFT", "OPEN", "EXPIRED", "TERMINATED", "CANCELLED"], { default: "DRAFT" }), field("wage", "Contract wage", "money"), field("currency", "Currency", "text", { default: "INR" }), select("wageBasis", "Wage basis", ["MONTHLY", "HOURLY", "DAILY", "ANNUAL"], { default: "MONTHLY" }), select("payFrequency", "Pay frequency", frequencies, { default: "MONTHLY" }), relation("salaryStructureId", "Salary structure", "structures", optional), relation("workingScheduleId", "Working schedule", "schedules"), field("terms", "Contract terms", "textarea", optional), field("terminationReason", "Termination reason", "textarea", optional)] },
  schedules: { help: "Schedule code example: DAY_SHIFT. Lowercase letters become uppercase and spaces become underscores when saved. Use 2–40 characters, starting with a letter.", title: "Working schedules", singular: "working schedule", columns: [["name", "Full name"], ["type", "Type"], ["weeklyHours", "Weekly hours"], ["code", "Code"], ["timezone", "Timezone"], ["isActive", "Active"]], fields: [field("code", "Code"), field("name", "Full name"), select("type", "Schedule type", ["FULL_TIME", "PART_TIME", "FLEXIBLE", "SHIFT"], { default: "FULL_TIME" }), field("timezone", "Timezone", "text", { default: "Asia/Kolkata" }), field("lateGraceMinutes", "Late grace (minutes)", "number", { default: 0 }), field("overtimeThresholdMinutes", "Overtime grace (minutes)", "number", { default: 0 }), note, active], arrays: "schedule", archive: true },
  assignments: { title: "Schedule assignments", singular: "schedule assignment", columns: [["employee", "Employee"], ["workingSchedule.name", "Schedule"], ["startDate", "Start"], ["endDate", "End"]], fields: [employee, relation("workingScheduleId", "Schedule", "schedules"), ...range] },
  categories: { title: "Salary categories", singular: "salary category", columns: [["code", "Code"], ["name", "Name"], ["type", "Type"]], fields: [...named, select("type", "Category type", ["BASIC", "ALLOWANCE", "GROSS", "DEDUCTION", "EMPLOYER_CONTRIBUTION", "NET", "OTHER"]), note] },
  structures: { title: "Salary structures", singular: "salary structure", columns: [["code", "Code"], ["name", "Name"], ["category.name", "Category"], ["sequence", "Sequence"], ["currency", "Currency"], ["payFrequency", "Frequency"], ["revision", "Revision"], ["isActive", "Active"]], fields: [...named, relation("categoryId", "Category", "categories", optional), field("sequence", "Sequence", "number", { default: 10 }), field("currency", "Currency", "text", { default: "INR" }), select("payFrequency", "Pay frequency", frequencies, { default: "MONTHLY" }), note, active], arrays: "rules", archive: true },
  rules: { title: "Salary rules", singular: "salary rule", columns: [["code", "Code"], ["name", "Name"], ["category.name", "Category"], ["computationMethod", "Calculation"], ["effect", "Effect"], ["isActive", "Active"]], fields: [...named, relation("categoryId", "Category", "categories"), select("effect", "Effect", ["EARNING", "DEDUCTION", "EMPLOYER_COST", "INFORMATIONAL"], { default: "EARNING" }), field("sequence", "Default sequence", "number", { default: 10 }), select("computationMethod", "Calculation method", ["FIXED", "PERCENTAGE", "FORMULA", "INPUT"], { default: "FORMULA" }), field("fixedAmount", "Fixed amount", "money", { ...optional, when: ["computationMethod", "FIXED"] }), field("percentageRate", "Percentage rate", "money", { ...optional, when: ["computationMethod", "PERCENTAGE"] }), field("percentageBase", "Percentage base expression", "text", { ...optional, when: ["computationMethod", "PERCENTAGE"] }), field("formula", "Amount formula", "text", { default: "WAGE", ...optional, when: ["computationMethod", "FORMULA"] }), field("quantityFormula", "Quantity formula (default 1)", "text", optional), select("conditionMethod", "Apply rule when", ["ALWAYS", "RANGE", "FORMULA"], { default: "ALWAYS" }), field("conditionFormula", "Condition formula (zero = false)", "text", { ...optional, when: ["conditionMethod", "FORMULA"] }), field("conditionBase", "Condition base", "text", { ...optional, when: ["conditionMethod", "RANGE"] }), field("conditionMinimum", "Condition minimum", "money", { ...optional, when: ["conditionMethod", "RANGE"] }), field("conditionMaximum", "Condition maximum", "money", { ...optional, when: ["conditionMethod", "RANGE"] }), field("appearsOnPayslip", "Show on payslip", "checkbox", { default: true }), note, active], archive: true, help: "Use WAGE for prorated payable wage, CONTRACT_WAGE for the full contract wage, WORKED_HOURS, WORKED_DAYS, SCHEDULED_DAYS, PAID_DAYS, GROSS, NET, variable input codes, or earlier rule codes. Expressions support + − × / and parentheses. For INPUT method, provide values directly via variable inputs during payroll." },
  "leave-types": { title: "Time-off types", singular: "time-off type", columns: [["code", "Code"], ["name", "Name"], ["unit", "Unit"], ["requestApprovalPolicy", "Approval"], ["paidPercentage", "Pay %"]], fields: [...named, select("unit", "Unit", ["DAYS", "HOURS"], { default: "DAYS" }), field("requiresAllocation", "Requires an approved allocation", "checkbox", { default: true }), select("requestApprovalPolicy", "Request approval", ["AUTOMATIC", "SINGLE_APPROVAL", "TWO_LEVEL_APPROVAL"], { default: "SINGLE_APPROVAL" }), select("allocationApprovalPolicy", "Allocation approval", ["SINGLE_APPROVAL", "TWO_LEVEL_APPROVAL"], { default: "SINGLE_APPROVAL" }), select("payrollTreatment", "Payroll treatment", ["PAID", "UNPAID", "PARTIALLY_PAID"], { default: "PAID" }), field("paidPercentage", "Paid percentage", "number", { default: 100 }), field("allowHalfDay", "Allow half days", "checkbox", { default: true }), note, active], archive: true },
  allocations: { title: "Leave allocations", singular: "leave allocation", columns: [["employee", "Employee"], ["leaveType.name", "Type"], ["amount", "Allocated"], ["remaining", "Remaining"], ["unit", "Unit"], ["validUntil", "Expires"], ["status", "Status"]], fields: [employee, relation("leaveTypeId", "Leave type", "leaveTypes"), field("name", "Allocation name"), field("amount", "Amount", "money"), field("validFrom", "Valid from", "date"), field("validUntil", "Valid until", "date", optional), field("reason", "Reason", "textarea", optional)], noEdit: true, workflow: "leave" },
  leave: { title: "Time-off requests", singular: "time-off request", columns: [["employee", "Employee"], ["leaveType.name", "Type"], ["startDate", "Start"], ["endDate", "End"], ["duration", "Duration"], ["status", "Status"]], fields: [employee, relation("leaveTypeId", "Leave type", "leaveTypes"), field("startDate", "Start date", "date"), field("endDate", "End date", "date"), select("fraction", "Day portion", ["1", "0.5"], { default: "1" }), field("hoursPerDay", "Hours per day (hourly leave only)", "money", optional), field("reason", "Reason", "textarea", optional)], noEdit: true, workflow: "leave" },
  attendance: { title: "Attendance sessions", singular: "attendance session", columns: [["day.employee", "Employee"], ["day.employee.department.name", "Department"], ["day.employee.manager.firstName", "Manager"], ["checkIn", "Check-in"], ["checkOut", "Check-out"], ["day.workedHours", "Worked hours"], ["day.overtimeHours", "Overtime"], ["day.status", "Status"]], fields: [employee, field("checkIn", "Check-in", "datetime-local"), field("checkOut", "Check-out", "datetime-local", optional), field("breakMinutes", "Unpaid break minutes", "number", { default: 0 }), field("notes", "Notes", "textarea", optional), field("reason", "Correction reason (required when editing)", "text", optional)] },
  payruns: { title: "Payruns", singular: "payrun", columns: [["name", "Name"], ["period.startDate", "Period start"], ["period.endDate", "Period end"], ["salaryStructure.name", "Structure"], ["_count.payslips", "Payslips"], ["currency", "Currency"], ["status", "Status"]], fields: [field("name", "Payrun name"), field("startDate", "Period start", "date"), field("endDate", "Period end", "date"), field("paymentDate", "Planned payment date", "date", optional), relation("salaryStructureId", "Salary structure", "structures"), relation("departmentId", "Department scope", "departments", optional), select("employeeType", "Employee type scope", types, optional), field("notes", "Notes", "textarea", optional)], arrays: "employees", noEdit: true, workflow: "payroll" },
  payslips: { title: "Payslips", singular: "payslip", columns: [["number", "Number"], ["employee", "Employee"], ["periodStart", "Period start"], ["grossAmount", "Gross"], ["deductionAmount", "Deductions"], ["netAmount", "Net"], ["currency", "Currency"], ["status", "Status"]], fields: [], noCreate: true, noEdit: true, help: "Payslips are generated when a payrun is computed. Open a payslip for its frozen salary breakdown, variable inputs, and print view." },
  roles: { title: "Role catalog", singular: "role", columns: [["code", "Role"], ["name", "Name"], ["description", "Description"], ["_count.users", "Accounts"]], fields: [field("name", "Display name"), note], noCreate: true, help: "Role codes define access levels. Assign them to accounts above. The Administrator role always retains full access to this dashboard." },
  activity: { title: "Audit history", singular: "audit event", columns: [["action", "Action"], ["entityType", "Record type"], ["entityId", "Record ID"], ["actor.name", "Changed by"], ["createdAt", "Time"]], fields: [], noCreate: true, noEdit: true },
};
export const tabs = { employees: ["employees", "departments", "positions"], schedules: ["schedules", "assignments"], leave: ["leave", "allocations", "leave-types"], rules: ["rules", "categories"] };
export function display(value, key = "") {
  if (value == null || value === "") return "—";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "object") return value.firstName ? `${value.firstName} ${value.lastName}` : value.name || value.title || "—";
  if (/^\d{4}-\d{2}-\d{2}T/.test(String(value))) return /checkIn|checkOut|createdAt/.test(key) ? new Date(value).toLocaleString() : new Date(value).toLocaleDateString();
  if (/Amount|wage|remaining|weeklyHours/.test(key)) return Number(value).toLocaleString(undefined, { maximumFractionDigits: 2 });
  return String(value).includes("_") ? human(value) : String(value);
}
export function valueAt(row, key) {
  if (key === "taken") return Math.max(0, Number(row.amount) - Number(row.remaining ?? row.amount));
  if (key === "day.workedHours") return (row.day?.workedMinutes / 60).toFixed(2);
  if (key === "day.overtimeHours") return (row.day?.overtimeMinutes / 60).toFixed(2);
  if (key === "sessionHours") return row.checkOut ? Math.max(0, (new Date(row.checkOut) - new Date(row.checkIn)) / 3600000 - row.breakMinutes / 60).toFixed(2) : "—";
  if (key === "checkoutStatus") return row.checkOut ? "Complete" : "Missing checkout";
  if (key === "effectiveStatus") { const today = new Date().toLocaleDateString("en-CA"); return row.status !== "OPEN" ? human(row.status) : [row.endDate, row.terminationDate].filter(Boolean).some(d => d.slice(0, 10) < today) ? "Expired" : row.startDate.slice(0, 10) > today ? "Upcoming" : "Active"; }

  if (key === "weeklyHours") return weeklyHours(row.lines);
  return key.split(".").reduce((v, k) => v?.[k], row);
}
