"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Tooltip, Legend } from "chart.js";
import { Bar } from "react-chartjs-2";
import { Activity, ArrowUpRight, CalendarDays, ChevronRight, Clock3, Leaf, LayoutDashboard, LoaderCircle, Menu, Play, RefreshCw, ShieldCheck, Square, UserRound, X } from "lucide-react";
import Brand from "@/components/admin/brand";
import WorkspaceSidebar from "@/components/admin/workspace-sidebar";
import { ThemeToggle, useTheme } from "@/components/admin/theme-provider";
import { human, display } from "@/components/admin/workspace-config";
import { getCurrentUser, logoutUser, workspaceHome } from "@/services/auth.service";
import { errorMessage } from "@/services/admin.service";
import { employeeApi } from "@/services/employee.service";
import "./employee.css";

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);
const navigation = [["overview", "My dashboard", LayoutDashboard], ["attendance", "My attendance", Clock3], ["leave", "Time-off requests", Leaf], ["balances", "Leave balances", CalendarDays], ["schedule", "Working schedule", Activity], ["profile", "My profile", UserRound]];
const labels = Object.fromEntries(navigation.map(([key, label]) => [key, label]));
const currentMonth = () => new Date().toLocaleDateString("en-CA").slice(0, 7);
const fmt = n => Number(n || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });
const shiftTime = n => `${String(Math.floor(n / 60)).padStart(2, "0")}:${String(n % 60).padStart(2, "0")}`;

function Dialog({ title, onClose, children, busy }) {
  const ref = useRef(null);
  useEffect(() => { const element = ref.current; element.showModal(); return () => element.close(); }, []);
  return <dialog ref={ref} className="pp-dialog pp-module-dialog" aria-label={title} onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><div className="pp-dialog-heading"><h2>{title}</h2><button className="pp-icon-button" disabled={busy} onClick={onClose} aria-label="Close dialog"><X /></button></div>{children}</dialog>;
}

function LeaveForm({ types, onClose, onSaved }) {
  const [typeId, setTypeId] = useState(""), [fraction, setFraction] = useState("1"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const type = types.find(t => t.id === Number(typeId));
  async function submit(event) {
    event.preventDefault(); setBusy(true); setError("");
    const form = new FormData(event.currentTarget);
    try { await employeeApi.requestLeave({ leaveTypeId: Number(typeId), startDate: form.get("start"), endDate: form.get("end"), fraction: type?.allowHalfDay ? fraction : "1", ...(type?.unit === "HOURS" ? { hoursPerDay: Number(form.get("hours")) } : {}), reason: form.get("reason") }); onSaved("Your time-off request has been submitted."); }
    catch (e) { setError(errorMessage(e)); setBusy(false); }
  }
  return <Dialog title="Request time off" onClose={onClose} busy={busy}><form className="pp-form" onSubmit={submit}><fieldset disabled={busy}><label htmlFor="leave-type">Leave type</label><select id="leave-type" required value={typeId} onChange={e => setTypeId(e.target.value)}><option value="">Select a leave type</option>{types.map(t => <option key={t.id} value={t.id}>{t.name} ({human(t.unit)})</option>)}</select><div className="pp-employee-form-grid"><label>Start date<input type="date" name="start" required /></label><label>End date<input type="date" name="end" required /></label></div>{type?.unit === "HOURS" ? <label>Hours per working day<input name="hours" type="number" required min="0.25" max="24" step="0.25" /></label> : type?.allowHalfDay && <label>Duration per working day<select value={fraction} onChange={e => setFraction(e.target.value)}><option value="1">Full day</option><option value="0.5">Half day</option></select></label>}<label>Reason<textarea name="reason" required maxLength={3000} placeholder="Tell your manager about your request" /></label><p className="pp-field-note">Duration follows your assigned working schedule. {type?.requiresAllocation ? "Approved requests use your allocated leave balance." : "This type does not require an allocation."}</p></fieldset>{error && <div className="pp-error" role="alert">{error}</div>}<div className="pp-dialog-actions"><button type="button" className="pp-button pp-button-outline" onClick={onClose} disabled={busy}>Cancel</button><button className="pp-button pp-button-primary" disabled={busy || !types.length}>{busy ? "Submitting…" : "Submit request"}</button></div></form></Dialog>;
}

function ContactForm({ profile, onSaved }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const fields = [["personalEmail", "Personal email", "email"], ["personalPhone", "Personal phone", "tel"], ["addressLine1", "Address", "text"], ["city", "City", "text"], ["postalCode", "Postal code", "text"], ["emergencyContactName", "Emergency contact", "text"], ["emergencyContactPhone", "Emergency phone", "tel"]];
  return <form className="pp-panel pp-settings-section pp-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); const values = new FormData(e.currentTarget); try { await employeeApi.updateProfile(Object.fromEntries(fields.map(([key]) => [key, values.get(key)?.trim() || null]))); onSaved("Your contact information was updated."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><h2>Contact & emergency information</h2><fieldset className="pp-employee-form-grid" disabled={busy}>{fields.map(([key, label, type]) => <label key={key}>{label}<input name={key} type={type} defaultValue={profile[key] || ""} maxLength={200} /></label>)}</fieldset>{error && <div className="pp-error" role="alert">{error}</div>}<div className="pp-dialog-actions"><a href="/forgot-password" className="pp-button pp-button-outline">Reset password</a><button className="pp-button pp-button-primary" disabled={busy}>{busy ? "Saving…" : "Save contact details"}</button></div></form>;
}

export default function EmployeeDashboard() {
  const router = useRouter(), { resolved } = useTheme();
  const [user, setUser] = useState(null), [data, setData] = useState(null), [section, setSection] = useState("overview"), [month, setMonth] = useState(currentMonth), [revision, setRevision] = useState(0);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [mobile, setMobile] = useState(false), [dialog, setDialog] = useState(null), [clockNow, setClockNow] = useState(0);
  useEffect(() => { let active = true; getCurrentUser().then(({ user }) => { if (!active) return; if (!["EMPLOYEE", "ADMIN"].includes(user.role)) return router.replace(workspaceHome(user.role)); setUser(user); }).catch(e => { if (active) { if (e.response?.status === 401) router.replace("/login"); else setError(errorMessage(e)); } }); return () => { active = false; }; }, [router]);
  useEffect(() => { if (!user) return; let active = true; const task = setTimeout(() => { setLoading(true); employeeApi.dashboard(month).then(result => { if (active) { setData(result); setError(""); } }).catch(e => { if (active) { setError(errorMessage(e)); if (e.response?.status === 401) router.replace("/login"); } }).finally(() => { if (active) setLoading(false); }); }, 0); return () => { active = false; clearTimeout(task); }; }, [user, month, revision, router]);
  useEffect(() => { const tick = setInterval(() => setClockNow(Date.now()), 1000); return () => clearInterval(tick); }, []);
  useEffect(() => { const refresh = () => { if (document.visibilityState === "visible") setRevision(v => v + 1); }; const timer = setInterval(refresh, 60000); window.addEventListener("focus", refresh); return () => { clearInterval(timer); window.removeEventListener("focus", refresh); }; }, []);
  const refresh = () => setRevision(v => v + 1);
  const saved = message => { setDialog(null); setNotice(message); refresh(); };
  function navigate(next) { setSection(next); setMobile(false); setNotice(""); }
  async function checkIn() { setBusy(true); setError(""); try { await employeeApi.clock({ action: "check-in" }); saved("You are checked in. Have a good working day."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  const elapsed = data?.openSession ? Math.max(0, Math.floor(((clockNow || new Date(data.generatedAt).getTime()) - new Date(data.openSession.checkIn)) / 1000)) : 0;
  const elapsedLabel = `${String(Math.floor(elapsed / 3600)).padStart(2, "0")}:${String(Math.floor(elapsed / 60) % 60).padStart(2, "0")}:${String(elapsed % 60).padStart(2, "0")}`;
  if (!user) return <main className="pp-access-loading"><Brand href="/login" /><p role="status">{error || "Opening your employee workspace…"}</p></main>;
  const metric = data?.metrics, profile = data?.profile;
  const initials = user.name.split(" ").filter(Boolean).slice(0, 2).map(n => n[0]).join("");
  const dateTime = value => value ? new Intl.DateTimeFormat(undefined, { timeZone: data.settings.timezone, month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "Still working";
  const cards = metric ? [["Days present", metric.presentDays, `${metric.absentDays} recorded absent days`, Clock3, "attendance", "green"], ["Hours worked", fmt(metric.workedHours), `${fmt(metric.overtimeHours)} overtime hours`, Activity, "attendance", "blue"], ["Available leave", `${fmt(metric.availableDays)} days`, `${fmt(metric.availableHours)} hours in hourly allocations · available today`, Leaf, "balances", "violet"], ["Pending requests", metric.pendingRequests, `${fmt(metric.approvedLeaveDays)} approved days this month`, CalendarDays, "leave", "orange"]] : [];
  function requestsTable(compact = false) { const rows = compact ? data.requests.slice(0, 5) : data.requests; return rows.length ? <div className="pp-table-scroll"><table className="pp-table"><thead><tr><th>Leave type</th><th>Dates</th><th>Duration</th><th>Status</th>{!compact && <th>Details & actions</th>}</tr></thead><tbody>{rows.map(r => <tr key={r.id}><td>{r.leaveType.name}</td><td>{display(r.startDate)} – {display(r.endDate)}</td><td>{fmt(r.duration)} {human(r.unit).toLowerCase()}</td><td><span className={`pp-badge ${r.status === "APPROVED" ? "pp-badge-green" : "pp-badge-neutral"}`}>{human(r.status)}</span></td>{!compact && <td><p>{r.reason}</p>{(r.refusalReason || r.cancellationReason) && <small>{r.refusalReason || r.cancellationReason}</small>}{["SUBMITTED", "FIRST_APPROVED"].includes(r.status) && <button className="pp-text-button" onClick={() => setDialog({ type: "cancel", request: r })}>Withdraw request</button>}</td>}</tr>)}</tbody></table></div> : <div className="pp-empty"><h3>No requests for this month</h3><p>Plan your next time off with a new request.</p></div>; }
  return <div className="pp-dashboard pp-hr-dashboard pp-employee-dashboard">
    <WorkspaceSidebar
      groups={[["MY WORKSPACE", navigation]]} section={section} onNavigate={navigate} mobileOpen={mobile} onMobileChange={setMobile}
      organizationName={data?.settings.organizationName} workspaceLabel="Employee workspace" navigationLabel="Employee navigation"
      homeHref="/employee/dashboard" user={user} role="Employee" signingOut={busy}
      onSignOut={async () => { setBusy(true); try { await logoutUser(); router.replace("/login"); } catch (e) { setError(errorMessage(e)); setBusy(false); } }}
    />
    <div className="pp-workspace-main"><header className="pp-topbar"><div className="pp-topbar-location"><button className="pp-icon-button pp-mobile-menu" aria-label="Open navigation" aria-expanded={mobile} aria-controls="workspace-sidebar" onClick={() => setMobile(true)}><Menu /></button><span className="pp-topbar-mark"><UserRound /></span><div className="pp-topbar-location-text"><span className="pp-topbar-eyebrow">Employee workspace</span><nav className="pp-breadcrumb" aria-label="Breadcrumb"><button className="pp-breadcrumb-home" onClick={() => navigate("overview")}>Workspace</button><ChevronRight size={14} /><strong>{labels[section]}</strong></nav></div></div><div className="pp-topbar-actions"><span className="pp-live-status"><span className="pp-dot" />My workday</span><ThemeToggle /><span className="pp-avatar">{initials}</span></div></header>
      <main className="pp-main-content"><div className="pp-page-heading"><div><p className="pp-eyebrow">YOUR PEOPLEPAY360</p><h1>{section === "overview" ? `Hello, ${profile?.firstName || user.name.split(" ")[0]}` : labels[section]}<span className="pp-heading-dot">.</span></h1><p>{section === "overview" ? "Your workday, time off and team details, all in one place." : "Keep track of your records and manage your working day."}</p></div><button className="pp-button pp-button-primary" disabled={!data} onClick={() => setDialog({ type: "leave" })}><Leaf size={17} />Request time off</button></div>
        {error && <div className="pp-error" role="alert">{error}<button onClick={refresh}>Retry</button></div>}{notice && <p className="pp-module-notice" role="status">{notice}</p>}
        <div className="pp-filter-bar"><div className="pp-period-filter"><CalendarDays size={17} /><label htmlFor="employee-month">Reporting month</label><input id="employee-month" type="month" min="2000-01" max="2099-12" value={month} onChange={e => { if (e.target.value) setMonth(e.target.value); }} /></div><div className="pp-filter-right"><span className="pp-field-note">{data ? `Updated ${new Date(data.generatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : ""}</span><button className="pp-icon-button" aria-label="Refresh employee dashboard" disabled={loading} onClick={refresh}><RefreshCw size={18} className={loading ? "pp-spin" : ""} /></button></div></div>
        {!data ? <div className="pp-panel pp-empty" role="status">{loading ? <><LoaderCircle className="pp-spin" /><p>Loading your records…</p></> : <><ShieldCheck size={30} /><h3>Your workspace needs an employee profile</h3><p>Your administrator can link your login to your employee record.</p></>}</div> : <>
          {["overview", "attendance"].includes(section) && <section className="pp-panel pp-employee-clock"><div><span className={`pp-badge ${data.openSession ? "pp-badge-green" : "pp-badge-neutral"}`}>{data.openSession ? "Checked in" : "Checked out"}</span><h2>{data.openSession ? elapsedLabel : "Ready for your workday?"}</h2><p>{data.openSession ? `Started ${dateTime(data.openSession.checkIn)}` : data.schedule ? `${data.schedule.name} · ${fmt(data.schedule.todayMinutes / 60)} scheduled hours today` : "Ask HR to assign your working schedule."}</p><small>{data.settings.timezone} · Session time includes breaks until checkout</small></div><button className="pp-button pp-button-primary" disabled={busy || (!data.openSession && !data.schedule)} onClick={() => data.openSession ? setDialog({ type: "checkout" }) : checkIn()}>{data.openSession ? <Square size={17} /> : <Play size={17} />}{data.openSession ? "Check out" : "Check in"}</button></section>}
          {section === "overview" && <><section className="pp-metrics" aria-label="Employee key performance indicators" aria-busy={loading}>{cards.map(([label, value, note, Icon, target, tone]) => <article className="pp-metric" key={label}><div className="pp-metric-top"><span>{label}</span><span className={`pp-icon-box pp-tone-${tone}`}><Icon size={20} /></span></div><strong className="pp-kpi-value" key={value}>{value}</strong><p>{note}<button aria-label={`View ${label.toLowerCase()}`} onClick={() => navigate(target)}><ArrowUpRight size={16} /></button></p></article>)}</section><section className="pp-overview-grid"><article className="pp-panel"><div className="pp-panel-heading"><div><h2>Your working hours</h2><p>Closed attendance sessions · {month}</p></div><Activity size={20} /></div><div className="pp-hr-chart"><Bar data={{ labels: data.trend.map(d => d.date.slice(-2)), datasets: [{ label: "Hours worked", data: data.trend.map(d => d.hours), backgroundColor: "#699d80", borderRadius: 5 }] }} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { ticks: { color: resolved === "dark" ? "#b7cabc" : "#546c5d", maxTicksLimit: 15 } }, y: { beginAtZero: true, ticks: { color: resolved === "dark" ? "#b7cabc" : "#546c5d" } } } }} role="img" aria-label="Hours worked each day. My attendance provides the detailed records." /></div></article><article className="pp-panel pp-settings-section"><h2>Your team & work</h2><div className="pp-detail-grid">{[["Department", profile.department?.name], ["Job position", profile.jobPosition?.title], ["Manager", profile.manager ? `${profile.manager.firstName} ${profile.manager.lastName}` : null], ["Work location", profile.workLocation], ["Attendance health", metric.attendanceRate === null ? "No recorded days" : `${metric.attendanceRate}%`], ["Days late", metric.lateDays]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value ?? "Unassigned"}</strong></div>)}</div><button className="pp-text-button" onClick={() => navigate("profile")}>View my profile <ArrowUpRight size={16} /></button></article></section><section className="pp-panel"><div className="pp-panel-heading"><div><h2>Your recent time off</h2><p>Requests in the selected month</p></div><button className="pp-text-button" onClick={() => navigate("leave")}>View all requests</button></div>{requestsTable(true)}</section></>}
          {section === "attendance" && <section className="pp-panel"><div className="pp-panel-heading"><div><h2>Attendance history</h2><p>{fmt(metric.workedHours)} hours worked · {metric.presentDays} present days · {metric.lateDays} late days</p></div></div><div className="pp-table-scroll"><table className="pp-table"><thead><tr><th>Date</th><th>Status</th><th>Check in / out</th><th>Break</th><th>Worked hours</th><th>Late / overtime</th></tr></thead><tbody>{data.attendance.map(d => <tr key={d.id}><td>{display(d.workDate)}</td><td>{human(d.status)}</td><td>{d.entries.map(e => <p key={e.id}>{dateTime(e.checkIn)} → {dateTime(e.checkOut)}<small>{human(e.source)}</small></p>)}</td><td>{d.entries.reduce((n, e) => n + e.breakMinutes, 0)} min</td><td>{fmt(d.workedMinutes / 60)}</td><td>{d.lateMinutes} min / {fmt(d.overtimeMinutes / 60)} h</td></tr>)}</tbody></table>{!data.attendance.length && <p className="pp-empty">No attendance records for this month.</p>}</div><p className="pp-panel-footnote">Contact HR for attendance corrections. Open sessions are added to worked hours after checkout.</p></section>}
          {section === "leave" && <section className="pp-panel"><div className="pp-panel-heading"><div><h2>Time-off requests</h2><p>Follow approvals and withdraw pending requests.</p></div></div>{requestsTable()}</section>}
          {section === "balances" && <section className="pp-panel"><div className="pp-panel-heading"><div><h2>Leave allocations & balances</h2><p>Balances available today · days and hours are tracked separately</p></div></div><div className="pp-table-scroll"><table className="pp-table"><thead><tr><th>Allocation</th><th>Type</th><th>Allocated</th><th>Taken</th><th>Remaining</th><th>Validity</th><th>Status</th></tr></thead><tbody>{data.balances.map(b => <tr key={b.id}><td>{b.name}</td><td>{b.type}</td><td>{fmt(b.allocated)} {human(b.unit).toLowerCase()}</td><td>{fmt(b.taken)}</td><td>{fmt(b.remaining)}</td><td>{display(b.validFrom)} – {b.validUntil ? display(b.validUntil) : "No expiry"}</td><td>{human(b.status)}<small>{b.available ? "Available today" : "Not currently available"}</small></td></tr>)}</tbody></table>{!data.balances.length && <p className="pp-empty">No allocations yet. HR can assign leave allowances to your profile.</p>}</div></section>}
          {section === "schedule" && <section className="pp-panel"><div className="pp-panel-heading"><div><h2>{data.schedule?.name || "No working schedule assigned"}</h2><p>{data.schedule ? `${fmt(data.schedule.weeklyHours)} hours per week · ${data.schedule.timezone}` : "Contact HR to configure your working hours."}</p></div></div>{data.schedule && <div className="pp-table-scroll"><table className="pp-table"><thead><tr><th>Day</th><th>Start</th><th>End</th><th>Break</th><th>Hours</th></tr></thead><tbody>{data.schedule.lines.map(l => <tr key={l.id}><td>{human(l.day)}</td><td>{shiftTime(l.startMinute)}</td><td>{shiftTime(l.endMinute)}{l.endDayOffset ? " (+1 day)" : ""}</td><td>{l.breakMinutes} min</td><td>{fmt((l.endMinute + l.endDayOffset * 1440 - l.startMinute - l.breakMinutes) / 60)}</td></tr>)}</tbody></table></div>}</section>}
          {section === "profile" && <><section className="pp-panel pp-settings-section"><div className="pp-employee-profile-heading"><span className="pp-avatar">{initials}</span><div><h2>{profile.firstName} {profile.lastName}</h2><p>{profile.employeeCode} · {human(profile.status)}</p></div></div><div className="pp-detail-grid">{[["Work email", profile.workEmail], ["Work phone", profile.workPhone], ["Department", profile.department?.name], ["Position", profile.jobPosition?.title], ["Employment type", human(profile.employeeType)], ["Joined", display(profile.hireDate)]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || "Unassigned"}</strong></div>)}</div></section><ContactForm key={profile.id} profile={profile} onSaved={saved} /></>}
        </>}
        <footer className="pp-workspace-footer"><span>PeoplePay360 · Your people. Your workday.</span>{data?.settings.supportEmail ? <a href={`mailto:${data.settings.supportEmail}`}>Contact HR support</a> : <span>Employee workspace</span>}</footer>
      </main></div>
    {dialog?.type === "leave" && <LeaveForm types={data.leaveTypes} onClose={() => setDialog(null)} onSaved={saved} />}
    {["checkout", "cancel"].includes(dialog?.type) && <Dialog title={dialog.type === "checkout" ? "Finish your workday" : "Withdraw time-off request"} busy={busy} onClose={() => setDialog(null)}><form className="pp-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); const form = new FormData(e.currentTarget); try { if (dialog.type === "checkout") await employeeApi.clock({ action: "check-out", breakMinutes: Number(form.get("break")) }); else await employeeApi.cancelLeave(dialog.request.id, form.get("reason")); saved(dialog.type === "checkout" ? "Checked out. Your working hours are updated." : "Your request has been withdrawn."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}>{dialog.type === "checkout" ? <label>Total break minutes<input type="number" name="break" min="0" max="1440" defaultValue="0" required /></label> : <label>Reason<textarea name="reason" minLength={3} maxLength={1000} required /></label>}{error && <div className="pp-error" role="alert">{error}</div>}<div className="pp-dialog-actions"><button type="button" className="pp-button pp-button-outline" disabled={busy} onClick={() => setDialog(null)}>Back</button><button className="pp-button pp-button-primary" disabled={busy}>{busy ? "Saving…" : dialog.type === "checkout" ? "Check out" : "Withdraw request"}</button></div></form></Dialog>}
  </div>;
}
